@startuml
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam DefaultFontName FG Virgil
skinparam shadowing false

Title Deployment Diagram Elements

actor actor
agent agent
artifact artifact
boundary boundary
card card
cloud cloud
component component
control control
database database
entity entity
file file
folder folder
frame frame
interface  interface
node node
package package
queue queue
stack stack
rectangle rectangle
storage storage
usecase usecase
@enduml