@startuml
skinparam actorStyle awesome

skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam DefaultFontName FG Virgil
skinparam shadowing false

title Example Use Case diagram
footer \n\n*not validated*

left to right direction
user1 --> (Usecase 1)
user2 --> (Usecase 2)

@enduml